@startuml payment_extsys_context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

System_Ext(payment_extsys, "Payment Provider", "Integrated online payment gateway")

@enduml
