development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=certify_d user=user_service password=user_service sslmode=disable
  dir: postgres
  table: migrations

production:
  dialect: postgres
  datasource: host=prodhost dbname=proddb user=${DB_USER} password=${DB_PASSWORD} sslmode=require
  dir: postgres
  table: migrations
