# TODO: remove password from code

development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=certify_d user=user_service password=user_service sslmode=disable
  dir: postgres
  table: migrations

staging:
  dialect: postgres
  datasource: host=localhost port=5433 dbname=certify_d user=user_service password=user_service sslmode=disable
  dir: postgres
  table: migrations
