postsubmits:
  - name: swagger-ui-deploy
    decorate: true
    clone_uri: "git@github.com:darrensemusemu/certify-d-api.git"
    run_if_changed: '^((api\/openapi-spec\/.*(yaml|yml|Dockerfile))|(\.prow\/swagger[-]ui\.yaml))$'
    skip_report: false
    context: swagger-ui
    max_concurrency: 1
    spec:
      containers:
        - name: skaffold
          image: "gcr.io/k8s-skaffold/skaffold:v1.38.0"
          command: ["/bin/sh", "-c", "./scripts/skaffold-deploy.sh"]
          env:
            - name: CLUSTER_DEV_NAME
              value: main-cluster
            - name: PROJECT_DEV_NAME
              value: darrensemusemu-infra
            - name: PROJECT_DEV_REGION
              value: europe-west1-b
            - name: SERVICE_NAME
              value: swagger-ui
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/skaffold-service-account.json
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: service-account
              mountPath: /secrets
      volumes:
        - name: service-account
          secret:
            secretName: scaffold-service-account
      restartPolicy: Always
    branches:
      - main
    skip_branches: []
    
