presubmits:
  # - name: openapi-spec-validate
  # postsubmits:
  - name: swagger-ui-deploy
    decorate: true
    always_run: true
    run_if_changed: "/.*\/openapi-spec\/.*(.yaml|.yml|Dockerfile)|.prow\/swagger-ui.yaml$"
    skip_report: false
    context: swagger-ui
    max_concurrency: 1
    spec:
      containers:
        - name: skaffold
          image: "gcr.io/k8s-skaffold/skaffold:v1.38.0"
          command: ["/bin/sh", "-c"]
          args:
            - |
              gcloud auth activate-service-account --key-file=/secrets/scaffold-service-account.json &&
              gcloud container clusters get-credentials $CLUSTER_DEV_NAME --region europe-west1-b &&
              kubectl config get-contexts
          env:
            - name: $CLUSTER_DEV_NAME
              value:  main-cluster
          resources:
            limits:
              cpu: 64m
              memory: 100Mi
            requests:
              cpu: 64m
              memory: 100Mi
          volumeMounts:
            - name: service-account
              mountPath: /secrets
      volumes:
        - name: service-account
          secret:
            secretName: scaffold-service-account
      restartPolicy: Always
    branches: []
    skip_branches: []
    # trigger: "(?m)qux test this( please)?"
    # rerun_command: "qux test this please"

apiVersion: v1
kind: Pod
metadata:
  name: "MYAPP"
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
    - name: MYAPP
      image: "debian-slim:latest"
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: MYAPP
              key: DB_HOST
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
  restartPolicy: Always
