presubmits:
  - name: swagger-ui-deploy
    decorate: true
    clone_uri: "git@github.com:darrensemusemu/certify-d-api.git"
    run_if_changed: '((api\/openapi-spec\/.*)|(\.prow\/swagger[-]ui\.yaml))$'
    always_run: false
    skip_report: false
    context: swagger-ui
    max_concurrency: 1
    spec:
      containers:
        - name: skaffold
          image: "gcr.io/k8s-skaffold/skaffold:v1.38.0"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "one" && 
              gcloud auth activate-service-account --key-file=/secrets/skaffold-service-account.json &&
              echo "one" &&
              gcloud config set project $PROJECT_DEV_NAME &&
              echo "one" &&
              gcloud container clusters get-credentials $CLUSTER_DEV_NAME --region europe-west1-b &&
              echo "one" &&
              kubectl config get-contexts && 
              echo "two" &&
              export STATE=$(git rev-list -1 HEAD --abbrev-commit) &&  
              cat /secrets/skaffold-service-account.json  | grep  client_email && 
              skaffold build -m $SERVICE_NAME -p prod --file-output build-$STATE.json &&
              echo "three" &&
              skaffold deploy -m $SERVICE_NAME -a build-$STATE.json
          env:
            - name: CLUSTER_DEV_NAME
              value: main-cluster
            - name: PROJECT_DEV_NAME
              value: darrensemusemu-infra
            - name: PROJECT_DEV_REGION
              value: europe-west1-b
            - name: SERVICE_NAME
              value: swagger-ui
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/skaffold-service-account.json  
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: service-account
              mountPath: /secrets
      volumes:
        - name: service-account
          secret:
            secretName: scaffold-service-account
      restartPolicy: Always
    # branches: []z
    # skip_branches: []
    # trigger: "(?m)qux test this( please)?"

