presubmits:
  - name: swagger-ui-deploy
    decorate: true
    clone_uri: "git@github.com:darrensemusemu/certify-d-api.git"
    always_run: true
    skip_report: false
    context: swagger-ui
    max_concurrency: 1
    spec:
      containers:
        - name: skaffold
          image: "gcr.io/k8s-skaffold/skaffold:v1.38.0"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "one" &&
              gcloud auth activate-service-account --key-file=/secrets/skaffold-service-account.json &&
              echo "one" &&
              gcloud config set project $PROJECT_DEV_NAME &&
              echo "one" &&
              gcloud config set compute/zone $PROJECT_DEV_REGION && 
              echo "one" &&
              gcloud container clusters get-credentials $CLUSTER_DEV_NAME --region europe-west1-b &&
              echo "one" &&
              kubectl config get-contexts
          env:
            - name: CLUSTER_DEV_NAME
              value: main-cluster
            - name: PROJECT_DEV_NAME
              value: darrensemusemu-infra
            - name: PROJECT_DEV_REGION
              value: europe-west1-b
            - name: SERVICE_NAME
              value: swagger-ui
          resources:
            limits:
              cpu: 64m
              memory: 100Mi
            requests:
              cpu: 64m
              memory: 100Mi
          volumeMounts:
            - name: service-account
              mountPath: /secrets
      volumes:
        - name: service-account
          secret:
            secretName: scaffold-service-account
      restartPolicy: Always
    # branches: []z
    # skip_branches: []
    # trigger: "(?m)qux test this( please)?"

