# TODO: remove password from code

development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=certify_d user=postgres sslmode=disable
  dir: postgres
  table: migrations

staging:
  dialect: postgres
  datasource: host=localhost port=5433 dbname=certify_d user=postgres password=postgress sslmode=disable
  dir: postgres
  table: migrations
