add-enum-types = true
add-soft-deletes = true
no-tests = true
output = "pkg/models"
wipe = true

[psql]  
  dbname = "certify_d"
  host   = "localhost"
  port   = 5432
  user   = "upload_service"
  pass   = "upload_service"
  schema = "upload_service"
  blacklist = ["migrations"]
