repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: psql
    chart: bitnami/postgresql
    namespace: certify-d-dev
    values:
      - volumePermissions:
          enabled: true
      - image:
          tag: 14.4.0
      - auth:
          database: certify_d
          postgresPassword: postgress # TODO: set as env varible
