@startuml company_actor_context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(company_actor, "Company", "A registered company, with a commissioner of oaths",  $sprite="users")

@enduml