@startuml company_actor_relations
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Rel_R(company_actor, certify_sys, "Bids for approvals/declines, add employees")
Rel_R(company_actor, auth_extsys, "Provides credentials")

@enduml