// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// File defines model for File.
type File struct {
	Filename      *string             `json:"filename,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	NumberOfPages *string             `json:"numberOfPages,omitempty"`
	Type          *string             `json:"type,omitempty"`
	Url           *string             `json:"url,omitempty"`
}

// HealthOk defines model for HealthOk.
type HealthOk struct {
	Status *string `json:"status,omitempty"`
}

// A Problem Details object (RFC 7807)
type ProblemDetail struct {
	// A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
	Href *string `json:"href,omitempty"`

	// An absolute URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
	Title *string `json:"title,omitempty"`

	// An absolute URI that identifies the problem type
	Type *string `json:"type,omitempty"`
}

// Store defines model for Store.
type Store struct {
	Id       *openapi_types.UUID `json:"id,omitempty"`
	StoreRef *string             `json:"storeRef,omitempty"`
}

// A Problem Details object (RFC 7807)
type Error = ProblemDetail

// GetStoreResponse defines model for GetStoreResponse.
type GetStoreResponse = []struct {
	Files    *[]File             `json:"files,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	StoreRef *string             `json:"storeRef,omitempty"`
}

// PostStoreFileResponse defines model for PostStoreFileResponse.
type PostStoreFileResponse = []File

// PostStoreResponse defines model for PostStoreResponse.
type PostStoreResponse = Store

// PostStoreRequest defines model for PostStoreRequest.
type PostStoreRequest struct {
	StoreRef string `json:"storeRef"`
}

// HandleGetStoreParams defines parameters for HandleGetStore.
type HandleGetStoreParams struct {
	// Store reference
	StoreRef string `form:"storeRef" json:"storeRef"`
}

// HandleAddStoreJSONRequestBody defines body for HandleAddStore for application/json ContentType.
type HandleAddStoreJSONRequestBody PostStoreRequest
