// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Permission     string
	Role           string
	RolePermission string
	User           string
}{
	Permission:     "permission",
	Role:           "role",
	RolePermission: "role_permission",
	User:           "user",
}
