@startuml staff_actor_relations
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' !$level =

!if ($level == 1)

Rel_D(staff_actor, certify_sys, "Adds/Removes companies")

!elseif ($level == 2)

Rel_D(staff_actor, staff_webapp_cont, "Visits admin.certify-d.com")

!endif

@enduml
