development:
  dialect: postgres
  datasource: host=localhost port=5433 dbname=certify_d user=postgres password=postgress sslmode=disable
  dir: migrations/postgres
  table: migrations

production:
  dialect: postgres
  datasource: host=prodhost dbname=proddb user=${DB_USER} password=${DB_PASSWORD} sslmode=require
  dir: migrations/postgres
  table: migrations
