// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

const (
	KratosBearerAuthScopes = "KratosBearerAuth.Scopes"
)

// HealthOk defines model for HealthOk.
type HealthOk struct {
	Status *string `json:"status,omitempty"`
}

// A Problem Details object (RFC 7807)
type ProblemDetail struct {
	// A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
	Href *string `json:"href,omitempty"`

	// An absolute URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// The HTTP status code generated by the origin server for this occurrence of the problem.
	Status *int32 `json:"status,omitempty"`

	// A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
	Title *string `json:"title,omitempty"`

	// An absolute URI that identifies the problem type
	Type *string `json:"type,omitempty"`
}

// A Problem Details object (RFC 7807)
type Error = ProblemDetail
